version: '3.8'

services:
    api:
        container_name: WebAPI
        build:
            context: .
            dockerfile: src/Web/Dockerfile
        environment:
            RABBITMQ_URI: rabbitmq://api-eventbus:5672/
            RABBITMQ_USER: guest
            RABBITMQ_PASSWORD: guest
        ports:
            -   8080:8080
            -   8081:8081
        depends_on:
            -   redis
            -   rabbitmq
            

    redis:
        image: redis:latest
        container_name: distributed-cache
        expose:
            -   6379
        
    rabbitmq:
        image: rabbitmq:latest
        container_name: event-broker
        hostname: api-eventbus
        environment:
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASSWORD: guest
        expose:
            -   5672