USE Db_HealthCenterAPI;
GO

SET XACT_ABORT ON
BEGIN TRANSACTION

CREATE TABLE Users(
	Id					UNIQUEIDENTIFIER,
	UserName			NVARCHAR(250)		NOT NULL,
	NIC					VARCHAR(12)			NOT NULL	UNIQUE,
	EmailAddress		VARCHAR(255)		NOT NULL	UNIQUE,
	PhoneNumber			VARCHAR(10)			NOT NULL,
	[Role]				INT					NOT NULL,
	Gender				INT					NOT NULL,
	CreatedOn			DATETIME			NOT NULL,
	[CurrentTimeStamp]	UNIQUEIDENTIFIER	NOT NULL,

	CONSTRAINT Pk_User PRIMARY KEY(Id),
);

CREATE TABLE [Credentials](
	PasswordHash		VARBINARY(256)		NOT NULL,		
	Salt				VARBINARY(256)		NOT NULL,
	UserId				UNIQUEIDENTIFIER	NOT NULL UNIQUE,
	[CurrentTimeStamp]	UNIQUEIDENTIFIER	NOT NULL

	CONSTRAINT Fk_Credentials_User FOREIGN KEY(UserId) REFERENCES Users(Id) ON DELETE CASCADE
);

CREATE TABLE Doctors(
	Id					UNIQUEIDENTIFIER,
	DoctorName			NVARCHAR(250)		NOT NULL,
	[Description]		NVARCHAR(500)		NOT NULL,
	NIC					VARCHAR(12)			NOT NULL	UNIQUE,
	EmailAddress		VARCHAR(255)		NOT NULL	UNIQUE,
	PhoneNumber			VARCHAR(10)			NOT NULL,
	RegistrationNumber	NVARCHAR(15)		NOT NULL	UNIQUE,
	Gender				INT					NOT NULL,
	[CurrentTimeStamp]	UNIQUEIDENTIFIER	NOT NULL,

	CONSTRAINT Pk_Doctor PRIMARY KEY(Id)
);

CREATE TABLE [Sessions](
	Id					UNIQUEIDENTIFIER,
	SessionStart		DATETIME			NOT NULL,
	SessionEnd			DATETIME			NOT NULL,
	DoctorId			UNIQUEIDENTIFIER	NOT NULL,
	CurrentTimeStamp	UNIQUEIDENTIFIER	NOT NULL,

	CONSTRAINT Pk_Session PRIMARY KEY(Id),
	CONSTRAINT Fk_Session_Doctor FOREIGN KEY(DoctorId) REFERENCES Doctors(Id) ON DELETE CASCADE
);

CREATE TABLE Patients(
	Id					UNIQUEIDENTIFIER	NOT NULL,
	PatientName			NVARCHAR(250)		NOT NULL,
	NIC					VARCHAR(12)			NOT NULL	UNIQUE,
	EmailAddress		VARCHAR(255)		NOT NULL	UNIQUE,
	PhoneNumber			VARCHAR(10)			NOT NULL,
	DateOfBirth			DATETIME			NOT NULL,
	Gender				INT					NOT NULL,
	[CurrentTimeStamp]	UNIQUEIDENTIFIER	NOT NULL,

	CONSTRAINT Pk_Patient PRIMARY KEY(Id),
);

CREATE TABLE Appointments(
	Id					UNIQUEIDENTIFIER,
	AppointmentCreatedOn DATETIME			NOT NULL,
	PatientId			UNIQUEIDENTIFIER	NOT NULL,
	SessionId			UNIQUEIDENTIFIER	NOT NULL,
	[CurrentTimeStamp]	UNIQUEIDENTIFIER	NOT NULL

	CONSTRAINT Pk_Appointments PRIMARY KEY(Id),
	CONSTRAINT Fk_Appointment_Patient FOREIGN KEY(PatientId) REFERENCES Patients(Id) ON DELETE CASCADE,
	CONSTRAINT Fk_Appointment_Session FOREIGN KEY(SessionId) REFERENCES [Sessions](Id) ON DELETE CASCADE
);

CREATE INDEX IDX_AppointmentId ON Appointments(Id);
CREATE INDEX IDX_PatientNIC ON Patients(NIC);
CREATE INDEX IDX_UserNIC ON Users(NIC);
CREATE INDEX IDX_UserEmail ON Users(EmailAddress);
CREATE INDEX IDX_SessionId ON [Sessions](Id);
CREATE INDEX IDX_DoctorRegNo ON Doctors(RegistrationNumber);

COMMIT